name: poppins_app
description: "Une application pour la gestion des enfants en crèche."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^15.1.1
  
  # Firebase - Versions compatibles corrigées
  firebase_core: ^3.13.1
  firebase_auth: ^5.3.2
  firebase_auth_web: ^5.14.3
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.1
  firebase_storage_web: ^3.10.12
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^16.3.2
  
  # Autres dépendances
  http: ^1.3.0
  flutter_datetime_picker_plus: ^2.1.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  image_picker_web: ^4.0.0
  mime: ^2.0.0
  path: ^1.8.0
  url_launcher: ^6.1.10
  file_picker: ^10.1.2
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.0
  flutter_pdfview: ^1.3.1
  share_plus: ^11.0.0
  shared_preferences: ^2.2.0
  in_app_purchase: ^3.1.5
  flutter_app_badger: ^1.5.0
  
  # Ajouts pour le support d'email
  mailer: ^6.0.1
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Waltograph
      fonts:
        - asset: fonts/waltograph42.otf
        - asset: fonts/waltographUI.ttf
          style: normal
            
  assets:
    - assets/images/umbrella.png
    - assets/images/google.png
    - assets/images/biberon.png
    - assets/images/no_activities.png
    - assets/images/birthday_img.png
    - assets/images/logo.png
    - assets/images/Icone_Activites.png
    - assets/images/Icone_Actualites.png
    - assets/images/Icone_Ajout_Enfant.png
    - assets/images/Icone_Changes.png
    - assets/images/Icone_Dashboard.png
    - assets/images/Icone_Echanges.png
    - assets/images/Icone_Enfant_Present.png
    - assets/images/Icone_Horaires.png
    - assets/images/Icone_Photos.png
    - assets/images/Icone_Recaptitulatif.png
    - assets/images/Icone_Repas.png
    - assets/images/Icone_Sante.png
    - assets/images/Icone_Siestes.png
    - assets/images/Icone_Stock.png
    - assets/images/Icone_Transmission.png
    - assets/images/invitation.png
    - assets/images/maison_icon.png
    - assets/images/Icone_Structure.png
    - assets/images/parapluie.png